services:
  nginx:
    build:
      context: nginx
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    image: nginx:matcha
    container_name: matcha_nginx
    restart: on-failure
    ports:
      - 443:443
      - 8080:8080
    env_file:
      - .env
    secrets:
      - ssl_crt
      - ssl_key
    networks:
      front:
      back:
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "-k", "https://localhost:4433/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: frontend
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    image: frontend:matcha
    container_name: matcha_frontend
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./frontend:/usr/src/app
      - matcha_frontend_node_module:/usr/src/app/node_modules
    networks:
      front:
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 5s
      retries: 3

  backend:
    build:
      context: backend
      args:
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTPS_PROXY:-}
    image: backend:matcha
    container_name: matcha_backend
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_user_password
    working_dir: /usr/src/app
    secrets:
      - postgres_user_password
      - google_client_id
      - google_client_secret
      - jwt_secret
    volumes:
      - ./backend:/usr/src/app
      - matcha_backend_node_module:/usr/src/app/node_modules
    networks:
      back:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  database:
    image: postgres:16
    container_name: matcha_database
    restart: on-failure
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_user_password
      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256 --auth-local=scram-sha-256
    secrets:
      - postgres_user_password
    volumes:
      - data:/var/lib/postgresql/data
    networks:
      back:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  data:
  matcha_frontend_node_module:
  matcha_backend_node_module:

networks:
  front:
    driver: bridge
  back:
    driver: bridge

secrets:
  ssl_crt:
    file: ./secrets/matcha.crt
  ssl_key:
    file: ./secrets/matcha.key
  postgres_user_password:
    file: ./secrets/postgres_user_password.txt
  google_client_id:
    file: ./secrets/google_client_id
  google_client_secret:
    file: ./secrets/google_client_secret
  jwt_secret:
    file: ./secrets/jwt_secret
